stages:
    - build
    - test
    - deploy

cache:
  key: $CI_PIPELINE_ID
  paths:
    - build/
    - install/

oj-docker:
  stage: build
  image: python:latest
  cache:
    key: global
  paths:
    - openjournal-docker/
  script:
  - mkdir -p openjournal-docker
  - cd openjournal-docker
  - wget https://raw.githubusercontent.com/NotGlop/docker-drag/master/docker_pull.py
  - pip install --user requests      
  - python docker_pull.py openjournals/paperdraft   
                        
paper:
  stage: deploy
  image: docker:latest
  cache:
    key: global
  paths:
    - openjournal-docker/
  script:
    - docker load -i openjournal-docker/openjournals_paperdraft.tar
    - docker run --rm --volume ./:/data --user $(id -u):$(id -g) --env JOURNAL=joss openjournals/paperdraft
  artifacts:
    paths:
      - paper.pdf