stages:
    - build
    - test
    - deploy
        
build:
  stage: build
  image: schruste/ngsolve:latest
  cache:
    key: $CI_PIPELINE_ID
    paths:
      - build/
  script:
    - git submodule update --init --recursive
    - mkdir build
    - mkdir install    
    - cd build
    - cmake -DBUILD_NGSOLVE=OFF -DCMAKE_INSTALL_PREFIX=../install ..
    - make install

ctests-tutorials:
  stage: test
  image: schruste/ngsolve:latest
  cache:
    key: $CI_PIPELINE_ID
    paths:
      - build/
      - install/
  script:
    - bash .ci/ci_ctests.sh tutorial

  when: always
  allow_failure: false

ctests-mayfail:
  stage: test
  image: schruste/ngsolve:latest
  cache:
    key: $CI_PIPELINE_ID
    paths:
      - build/
      - install/
  script:
    - bash .ci/ci_ctests.sh mayfail
  when: always
  allow_failure: true

ctests-remaining:
  stage: test
  image: schruste/ngsolve:latest
  cache:
    key: $CI_PIPELINE_ID
    paths:
      - build/
      - install/
  script:
    -  bash .ci/ci_ctests.sh remaining
  when: always
  allow_failure: false

go4quads-tests:
  stage: test
  image: schruste/ngsolve:latest
  cache:
    key: $CI_PIPELINE_ID
    paths:
    - build/
    - install/
  script:
    - bash .ci/ci_ctests.sh go4quads-tests
  when: always
  allow_failure: false

metrics:
  stage: test
  image: schruste/ngsolve:latest
  cache:
    key: $CI_PIPELINE_ID
    paths:
    - build/
    - install/
  script:
    - export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${PWD}/install/lib/python3/dist-packages/xfem"
    - export PYTHONPATH="${PYTHONPATH}:${PWD}/install/lib/python3/dist-packages"
    - python3 /home/jovyan/.local/lib/python3.8/site-packages/share/ngsxfem/report/ngsxfem_report.py 2> metrics.txt
  artifacts:
    reports:
      metrics: metrics.txt
  when: always
  allow_failure: true
        
deploy:
  stage: deploy
  script:
  - echo " deploy"

cleanup:
  stage: deploy
  script:
    - echo " cleanup "
        
paper:
  stage: build
  image: docker:latest
  script:
    - docker run --rm --volume ./:/data --user $(id -u):$(id -g) --env JOURNAL=joss openjournals/paperdraft
  artifacts:
    paths:
      - paper.pdf