stages:
    - build
    - test
    - deploy
        
build:
  stage: build
  image: schruste/ngsolve:latest
  script:
    - git submodule update --init --recursive
    - mkdir build
    - mkdir install
    - cd build
    - cmake -DBUILD_NGSOLVE=OFF ..
    - make -j3
    - make install

ctests-tutorials:
  stage: test
  cache:
    key: "$CI_PIPELINE_ID"
    paths:
      - build/
  script:
    - bash .ci/ci_ctests.sh tutorial

  when: always
  allow_failure: false

ctests-mayfail:
  stage: test
  cache:
    key: "$CI_PIPELINE_ID"
    paths:
      - build/
  script:
    - bash .ci/ci_ctests.sh mayfail
  when: always
  allow_failure: true

ctests-remaining:
  stage: test
  cache:
    key: "$CI_PIPELINE_ID"
    paths:
      - build/
  script:
    -  bash .ci/ci_ctests.sh remaining
  when: always
  allow_failure: false

go4quads-tests:
  stage: test
  cache:
    key: "$CI_PIPELINE_ID"
    paths:
    - build/
  script:
    - bash .ci/ci_ctests.sh go4quads-tests
  when: always
  allow_failure: false

deploy:
  stage: deploy
  script:
  - echo " deploy"

cleanup:
  stage: deploy
  script:
    - echo " cleanup "

paper:
  stage: build
  image: openjournals/paperdraft
  script:
    - echo $PWD    
    - docker run --rm --volume $PWD:/data --user $(id -u):$(id -g) --env JOURNAL=joss openjournals/paperdraft
  artifacts:
    paths:
      - paper.pdf