beforescript:
  script:
    - echo " before script "

build:
  stage: build
  script:
    - echo " testenvironment "
    - uname -a
    - ls -al
    - pwd
    - gcc --version
    - mkdir build
    - cd build
    - use-netgen --run "gcc --version"
    - use-netgen --run "cmake ../."
    - use-netgen --run "make"

test1:
  stage: test
  script:
    - echo " test1 "

deploy:
  stage: deploy
  script:
  - echo " deploy "

cleanup:
  script:
    - echo " cleanup "
    - pwd
