beforescript:
  stage: build
  script:
    - echo " before script "
    - use-netgen --run "which ngscxx"
    - export TEST_ENV_VAR="testtesttest"
    - export | grep TEST_ENV_VAR

build:
  stage: build
  script:
    - echo " testenvironment "
    - export TEST_ENV_VAR="testtesttest_build"
    - export | grep TEST_ENV_VAR
    - uname -a
    - ls -al
    - pwd
    - gcc --version
    - mkdir build
    - mkdir inst
    - cd build
    #- NGSCXX=`use-netgen --run "which ngscxx"`
    - nix-shell -p blas liblapack gcc5 xorg.libXmu zlib cmake ccache ccacheWrapper mesa_glu mesa icu python35 suitesparse tcl-8_5 tk-8_5 --run "cmake -DINSTALL_DIR=`pwd`/../inst -DCMAKE_BUILD_TYPE=RELEASE -DUSE_CCACHE=ON -DUSE_GUI=ON ../."
    - nix-shell -p blas liblapack gcc5 xorg.libXmu zlib cmake ccache ccacheWrapper mesa_glu mesa icu python35 suitesparse tcl-8_5 tk-8_5 --run "make"
    - nix-shell -p blas liblapack gcc5 xorg.libXmu zlib cmake ccache ccacheWrapper mesa_glu mesa icu python35 suitesparse tcl-8_5 tk-8_5 --run "make install"

test1:
  stage: test
  script:
    - echo " test1 "

deploy:
  stage: deploy
  script:
  - echo " deploy "

cleanup:
  stage: deploy
  script:
    - echo " cleanup "
    - pwd
