stages:
    - build
    - test
    - deploy

cache:
  key: $CI_PIPELINE_ID
  paths:
    - build/
    - install/
                        
paper:
  stage: deploy
  image: docker:latest
  cache:
    key: global
    paths:
      - openjournal-docker/
    policy: pull        
  script:
    - ls -al .
    - ls -al *
    - docker load -i openjournal-docker/openjournals_paperdraft.tar
  artifacts:
    paths:
      - paper.pdf