stages:
    - build
    - test
    - deploy
        
build:
  stage: build
  image: ubuntu:latest
  script:
    - apt-get update -y
    - apt-get install python3 python3-pip git cmake -y
    - pip3 install ngsolve
    - export PYTHONPATH="$PYTHONPATH:/usr/local/lib/python3.10/site-packages"
    - python3 -c "import ngsolve"
    - git config --global --add safe.directory /builds/lehrenfeld/ngsxfem
    - git config --global --add safe.directory /builds/lehrenfeld/ngsxfem/external_dependencies/jupyter
    - git config --global --add safe.directory /builds/lehrenfeld/ngsxfem/external_dependencies/ngsolve
    - git submodule
    - git submodule update --init
    - mkdir build
    - mkdir install    
    - cd build
    - cmake -DBUILD_NGSOLVE=OFF -DCHECK_NGSOLVE_VERSION=OFF -DCMAKE_INSTALL_PREFIX=../install ..
    - make install
  artifacts:
    paths:
      - build
      - install
        
pages:
  stage: deploy
  image: ubuntu:latest
  script:
    - apt-get update -y
    - apt-get install python3 python3-pip -y
    - DEBIAN_FRONTEND="noninteractive" apt-get install python3-sphinx -y
    - pip3 install -r ./doc/sphinx/requirements.txt
    - export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${PWD}/install/lib/python3/dist-packages/xfem"
    - export PYTHONPATH="${PYTHONPATH}:${PWD}/install/lib/python3/dist-packages"
    - sphinx-apidoc -e -f -o doc/sphinx/xfem_doc install/lib/python3.10/site-packages/xfem/
    - sphinx-build doc/sphinx html
    - mv html public
  artifacts:
    paths:
      - public
  only:
    - sphinx # this job will affect only the 'sphinx' branch

