stages:
  - before_script
  - build
  - test1
  - deploy
  - cleanup

before_script:
  - echo " before script "

build:
  script:
    - echo " testenvironment "
    - uname -a
    - ls -al
    - pwd
    - gcc --version
    - mkdir build
    - cmake ../.
    - make

test1:
  script:
    - echo " test1 "

deploy:
  script:
  - echo " deploy "

cleanup:
  script:
    - echo " cleanup "
    - pwd
