stages:
    - build
    - test
    - deploy

cache:
  key: $CI_PIPELINE_ID
  paths:
    - build/
    - install/
    - openjournal-docker/
        
deploy:
  stage: deploy
  script:
  - echo " deploy"

cleanup:
  stage: deploy
  script:
    - echo " cleanup "

oj-docker:
  stage: build
  image: docker:latest
  script:
  - mkdir -p openjournal-docker
  - cd openjournal-docker
  - wget https://raw.githubusercontent.com/NotGlop/docker-drag/master/docker_pull.py
  - python docker_pull.py openjournals/paperdraft   
                        
paper:
  stage: deploy
  image: docker:latest
  script:
    - docker load openjournal-docker/openjournals_paperdraft.tar
    - docker run --rm --volume ./:/data --user $(id -u):$(id -g) --env JOURNAL=joss openjournals/paperdraft
  artifacts:
    paths:
      - paper.pdf