stages:
  - build
  - test1
  - cleanup

deploy:
  script:
  - echo " deploy "

before_script:
  - echo " before script "

test1:
  script:
    - echo " test1 "

build:
  script:
    - echo " testenvironment "
    - uname -a
    - ls -al
    - pwd

cleanup:
  script:
    - echo " cleanup "
    - pwd

testgcc:
  script:
    - gcc --version
