stages:
    - build
    - test
    - deploy
        
build:
  stage: build
  image: ngsxfem/ngsolve:latest
  script:
    - python3 -c "import ngsolve; print(ngsolve.__version__)"
    - git config --global --add safe.directory /builds/${CI_PROJECT_PATH}
    - git config --global --add safe.directory /builds/${CI_PROJECT_PATH}/external_dependencies/jupyter
    - git config --global --add safe.directory /builds/${CI_PROJECT_PATH}/external_dependencies/ngsolve
    - git submodule
    - git submodule update --init
    - mkdir build
    - mkdir install    
    - cd build
    - cmake -DBUILD_NGSOLVE=OFF -DCHECK_NGSOLVE_VERSION=OFF -DCMAKE_INSTALL_PREFIX=../install ..
    - make install
  artifacts:
    paths:
      - build
      - install
  needs: []  

ctests-demos:
  stage: test
  image: ngsxfem/ngsolve:latest
  script:
    - bash .ci/ci_ctests.sh demos
  when: always
  allow_failure: false
  needs: [build]  

ctests-mayfail:
  stage: test
  image: ngsxfem/ngsolve:latest
  script:
    - bash .ci/ci_ctests.sh mayfail
  when: always
  allow_failure: true
  needs: [build]  

ctests-pytests:
  stage: test
  image: ngsxfem/ngsolve:latest
  script:
    -  bash .ci/ci_ctests.sh pytests
  when: always
  allow_failure: false
  artifacts:
    when: always
    paths:
      - build/ctest-results.xml
    reports:
      junit: build/ctest-results.xml
  needs: [build]  

metrics:
  tags:
    - c5
  stage: test
  image: ngsxfem/ngsolve:latest
  script:
    - export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${PWD}/install/lib/python3.10/dist-packages/xfem"
    - export PYTHONPATH="${PYTHONPATH}:${PWD}/install/lib/python3.10/dist-packages"
    - python3 tests/ngsxfem_report.py 2> metrics.txt
  artifacts:
    reports:
      metrics: metrics.txt
  when: manual
  allow_failure: true
  needs: [build]  

codestyle-demos:
  stage: test
  image: ngsxfem/ngsolve:latest
  script:
    - pip3 install --user pycodestyle
    - export PATH="${PATH}:/home/jovyan/.local/bin"
    - pycodestyle demos/{*,spacetime/*,mpi/*}.py
  when: always
  allow_failure: true
  needs: []  

paper:
  stage: deploy
  image:
    name: openjournals/paperdraft
    entrypoint: [""] 
  script:
    - cd doc
    - /usr/local/bin/pandoc --defaults="$OPENJOURNALS_PATH"/docker-defaults.yaml --defaults="$OPENJOURNALS_PATH"/"$JOURNAL"/defaults.yaml -s -o paper.pdf paper.md
    - cp *.pdf ../
  artifacts:
    paths:
      - paper.pdf
  needs: []  

paper-appendix:
  stage: deploy
  image:
    name: schruste/latex
    entrypoint: [""] 
  script:
    - cd doc
    - pandoc --template latex.template --pdf-engine=lualatex -s -o feature-details.pdf feature-details.md        
    - pandoc --template latex.template --pdf-engine=lualatex -s -o literature.pdf literature.md
    - cp *.pdf ../
  artifacts:
    paths:
      - literature.pdf
      - feature-details.pdf
  needs: []  
        
        
pages:
  stage: deploy
  image: ngsxfem/ngsolve:latest
  script:
    - git config --global --add safe.directory /builds/${CI_PROJECT_PATH}
    - git config --global --add safe.directory /builds/${CI_PROJECT_PATH}/external_dependencies/jupyter
    - git config --global --add safe.directory /builds/${CI_PROJECT_PATH}/external_dependencies/ngsolve
    - git submodule
    - git submodule update --init
    - pip3 install --user -r ./doc/sphinx/requirements.txt
    - export PATH="$PATH:/home/jovyan/.local/bin"
    - export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${PWD}/install/lib/python3.10/dist-packages/xfem/" 
    - export PYTHONPATH="${PYTHONPATH}:${PWD}/install/lib/python3.10/dist-packages"
    - sphinx-apidoc -e -f -o doc/sphinx/xfem_doc install/lib/python3.10/dist-packages/xfem/
    - cp external_dependencies/jupyter/{aggregation,basics,intlset,cutfem,spacetime_fitted,spacetime_unfitted,mlset_basic,mlset_pde,unfmixed}.ipynb doc/sphinx/jupyter
    - cp external_dependencies/jupyter/helper.py doc/sphinx/jupyter
    - cp -r external_dependencies/jupyter/graphics doc/sphinx/jupyter
    - cp demos/{,aggregates/,mpi/,spacetime/,spdes/}*.py doc/sphinx/xfem_misc/
    - cp -r doc/graphics doc/sphinx/xfem_misc/
    - sphinx-build doc/sphinx html
    - cp doc/sphinx/bullets.css html/_static
    - rm -f html/.doctrees/nbsphinx/jupyter/*.ipynb
    - rm -f html/jupyter/*.ipynb
    - mv html public
  artifacts:
    paths:
      - public
  needs: [build,ctests-demos,ctests-pytests]  

  #only:
  #  - release # this job will affect only the 'sphinx' branch

pip_linux:
  #image: quay.io/pypa/manylinux2014_x86_64
  image: sameli/manylinux2014_x86_64_cuda_11      

  stage: deploy
  script:
    - ./.ci/build_pip.sh 38
    - ./.ci/build_pip.sh 39
    - ./.ci/build_pip.sh 310
    - ./.ci/build_pip.sh 311
    - /opt/python/cp39-cp39/bin/pip install twine
    - /opt/python/cp39-cp39/bin/python -m twine upload --skip-existing wheelhouse/* -u __token__ -p $PYPI_UPLOAD_TOKEN
    # - ./.ci/build_pip.sh 312
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  when: manual # we don't want to trigger this job in ngsxfem-simd: remove before merge
  needs: [ctests-demos, ctests-pytests]


docker_build:
  stage: deploy

  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
     
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "docker.gitlab.gwdg.de/lehrenfeld/ngsxfem/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH"
  
  when: manual 
  needs: [ctests-demos, ctests-pytests]  

