stages:
    - build
    - test
    - deploy
        
build:
  stage: build
  image: ngsxfem/ngsolve:latest
  script:
    - python3 -c "import ngsolve"
    - git config --global --add safe.directory /builds/lehrenfeld/ngsxfem
    - git config --global --add safe.directory /builds/lehrenfeld/ngsxfem/external_dependencies/jupyter
    - git config --global --add safe.directory /builds/lehrenfeld/ngsxfem/external_dependencies/ngsolve
    - git submodule
    - git submodule update --init --recursive
    - mkdir build
    - mkdir install    
    - cd build
    - cmake -DBUILD_NGSOLVE=OFF -DCMAKE_INSTALL_PREFIX=../install ..
    - make install
  artifacts:
    paths:
      - build
      - install
        
pages:
  stage: deploy
  image: ngsxfem/ngsolve:latest
  script:
    - python3 -m pip install -r ./doc/sphinx/requirements.txt
    - export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${PWD}/install/lib/python3/dist-packages/xfem"
    - export PYTHONPATH="${PYTHONPATH}:${PWD}/install/lib/python3/dist-packages"
    - sphinx-apidoc -e -f -o doc/sphinx/xfem_doc /code/ngs/install/lib/python3.10/site-packages/xfem/
    - sphinx-build doc/sphinx html
    - mv html public
  artifacts:
    paths:
      - public
  only:
    - sphinx # this job will affect only the 'master' branch

