name: Build, test (and publish release) of ngsxfem
on: [push]
jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"
  
  publish-pip-bin:
    needs: []
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64:latest
    if: github.ref == 'refs/heads/pip'
    steps:
      - name: update git
        run: yum -y install git
      - uses: actions/checkout@v2
      - name: safe.directory
        run: git config --global --add safe.directory /__w/ngsxfem/ngsxfem
      - name: pull submodules
        run: git submodule update --init --recursive
      - name: git describe --tags
        run: git describe --tags
      - name: Build and package xfem binaries for PyPI
        run: .ci/build_pip.sh
      - name: Publish binary distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: wheelhouse/