name: Build, test (and publish release) of ngsxfem
on: [push]
jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"
  
  publish-pip-bin:
    needs: []
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64:latest
    if: github.ref == 'refs/heads/pip'
    steps:
      - uses: actions/checkout@v2
      - name: Package xfem Sources for PyPI
        run: .ci/build_pip.sh
      - name: Publish source distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: wheelhouse/