name: Build, test (and publish release) of ngsxfem
on: [push]
jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"
	
  build:
    needs: configure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Build ngsxfem
        run: |
	  export NGSOLVE_VERSION=`python external_dependencies/ngsolve/tests/get_python_version_string_from_git.py external_dependencies/ngsolve`
	  pip install ngsolve>=$NGSOLVE_VERSION
	  pip install .
      - name: Cache build results
        uses: actions/cache@v2
        with:
          path: |
            build
            install
          key: ${{ runner.os }}-${{ github.sha }}-build-results
  
  publish-pip-bin:
    needs: []
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64:latest
    if: github.ref == 'refs/heads/pip'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: safe dir
        run: git config --global --add safe.directory /__w/ngsxfem/ngsxfem
      - name: git describe
        run: git describe --tags
      - name: Build and package xfem binaries for PyPI
        run: .ci/build_pip.sh
      - name: Publish binary distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN_2 }}
          packages_dir: wheelhouse/