name: Build, test (and publish release) of ngsxfem
on: [push]
jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"
  
  publish-pip-bin:
    needs: []
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64:latest
    if: github.ref == 'refs/heads/pip'
    steps:
      - name: Build and package xfem binaries for PyPI
        uses: actions/checkout@v2
        with:
	  fetch-depth: 0
	  submodules: recursive
        run: .ci/build_pip.sh
      - name: Publish binary distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: wheelhouse/