name: Build mac wheels

on: [push]

jobs:
  build_wheels_3.8:
    name: Build wheel for MacOS with Python 3.8
    runs-on: macos-11
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.15"
      TWINE_PASSWORD: ${{  secrets.TEST_PYPI  }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
          cache: 'pip'
      - name: Run build script
        run: .ci/build_pip_mac.sh 3.8
        shell: bash

  build_wheels_3.9:
    name: Build wheel for MacOS with Python 3.9
    runs-on: macos-11
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.15"
      TWINE_PASSWORD: ${{  secrets.TEST_PYPI  }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
          cache: 'pip'
      - name: Run build script
        run: .ci/build_pip_mac.sh 3.9
        shell: bash

  build_wheels_3.10:
    name: Build wheel for MacOS with Python 3.10
    runs-on: macos-11
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.15"
      TWINE_PASSWORD: ${{  secrets.TEST_PYPI  }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip'
      - name: Run build script
        run: .ci/build_pip_mac.sh 3.8
        shell: bash


