name: Build mac wheels
on: [push]
jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.python }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CIBW_ARCHS_MACOS: "x86_64"
      MACOSX_DEPLOYMENT_TARGET: "10.12"
    strategy:
      matrix:
        os: [macos-11]
    steps:
      -uses: actions/checkout@v3

      - name: Build wheels for CPython 3.10
        uses: pypa/cibuildwheel@v2.10.2
        env:
          CIBW_BUILD: "cp310-*"
          CIBW_BEFORE_BUILD: >-
            pip install ngsolve

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl