name: Build pip wheel (linux) and publish

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  
  publish-pip-bin:
    strategy:
      matrix:
        py: ['38', '39', '310', '311', '312']    
    needs: []
    runs-on: ubuntu-latest
    container:
      #image: quay.io/pypa/manylinux2014_x86_64:latest
      image: sameli/manylinux2014_x86_64_cuda_11.7      
    #if: github.ref == 'refs/heads/release/master'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: safe dir
        run: git config --global --add safe.directory /__w/ngsxfem/ngsxfem
      - name: git describe
        run: git describe --tags
      - name: Build and package xfem binaries for PyPI
        run: .ci/build_pip.sh ${{ matrix.py }}
      - name: Publish binary distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          password: ${{ secrets.PYPI_API_TOKEN_2 }}
          packages_dir: wheelhouse/
