name: Build mac wheels
on: [push]
jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.python }}-${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    buildplat:
        - [macos-10.15, macosx_*]
        python: ["cp38"] # , "cp39", "cp310", "cp311"]
    steps:
      - name: Checkout numpy
        uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.10.2
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl